-- AlterTable
ALTER TABLE "CLIENTES" ADD COLUMN     "imobiliaria_id" TEXT;

-- AlterTable
ALTER TABLE "CONTRATOS" ADD COLUMN     "imobiliaria_id" TEXT;

-- AlterTable
ALTER TABLE "IMOVEIS" ADD COLUMN     "imobiliaria_id" TEXT;

-- AlterTable
ALTER TABLE "PROPRIETARIOS" ADD COLUMN     "imobiliaria_id" TEXT;

-- AddForeignKey
ALTER TABLE "PROPRIETARIOS" ADD CONSTRAINT "PROPRIETARIOS_imobiliaria_id_fkey" FOREIGN KEY ("imobiliaria_id") REFERENCES "IMOBILIARIAS"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "IMOVEIS" ADD CONSTRAINT "IMOVEIS_imobiliaria_id_fkey" FOREIGN KEY ("imobiliaria_id") REFERENCES "IMOBILIARIAS"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CLIENTES" ADD CONSTRAINT "CLIENTES_imobiliaria_id_fkey" FOREIGN KEY ("imobiliaria_id") REFERENCES "IMOBILIARIAS"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CONTRATOS" ADD CONSTRAINT "CONTRATOS_imobiliaria_id_fkey" FOREIGN KEY ("imobiliaria_id") REFERENCES "IMOBILIARIAS"("id") ON DELETE SET NULL ON UPDATE CASCADE;
