-- AlterTable
ALTER TABLE "ALERTAS" ADD COLUMN     "imobiliaria_id" TEXT;

-- AlterTable
ALTER TABLE "AUDITORIA" ADD COLUMN     "imobiliaria_id" TEXT;

-- AlterTable
ALTER TABLE "DESPESAS" ADD COLUMN     "imobiliaria_id" TEXT;

-- AlterTable
ALTER TABLE "REAJUSTES" ADD COLUMN     "imobiliaria_id" TEXT;

-- AlterTable
ALTER TABLE "RECIBOS" ADD COLUMN     "imobiliaria_id" TEXT;

-- AddForeignKey
ALTER TABLE "RECIBOS" ADD CONSTRAINT "RECIBOS_imobiliaria_id_fkey" FOREIGN KEY ("imobiliaria_id") REFERENCES "IMOBILIARIAS"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "REAJUSTES" ADD CONSTRAINT "REAJUSTES_imobiliaria_id_fkey" FOREIGN KEY ("imobiliaria_id") REFERENCES "IMOBILIARIAS"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "DESPESAS" ADD CONSTRAINT "DESPESAS_imobiliaria_id_fkey" FOREIGN KEY ("imobiliaria_id") REFERENCES "IMOBILIARIAS"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ALERTAS" ADD CONSTRAINT "ALERTAS_imobiliaria_id_fkey" FOREIGN KEY ("imobiliaria_id") REFERENCES "IMOBILIARIAS"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "AUDITORIA" ADD CONSTRAINT "AUDITORIA_imobiliaria_id_fkey" FOREIGN KEY ("imobiliaria_id") REFERENCES "IMOBILIARIAS"("id") ON DELETE SET NULL ON UPDATE CASCADE;
